# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CicekSepeti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CicekSepeti
  pod 'Alamofire', '~> 4.7.0'
  pod 'SwiftyJSON', '~> 4.0.0'

end
